### ISSUE TITLE
gid of group paradox, and uid of user paradox

### ISSUE THREAD

**Issue by IoTPlay** [psyciknz/ParadoxIP150v2#11]
Hi, I run multiple docker containers on a Pi. I first create a group and user `paradox`, then fire up the container. Problem is, the docker container's user, also paradox, and the group, defaults to uid & gid of `999`. For me to interact between the host's folder, the uid / gid needs to be the same. I cannot make the uid/gid on the RPi host, as the gid is reserved for SPI.

Would it be possible to add a gid/uid higher, maybe 1884 and 1884, then when I create the paradox user on the host prior to firing up the docker file, I can create the paradox uid/gid with the same uid/gid?

In your Dockerfile.arm64v8, replace the command 
```
RUN groupadd -r paradox && useradd -r -g paradox paradox
```
with:
```
RUN groupadd -r -g 1884 paradox && useradd -r -g -u 1884 paradox paradox
```

**Comment by IoTPlay** [comment]
I will

**Comment by psyciknz** [comment]
What interaction are you needing where the group/uid needs to be set?

**Comment by IoTPlay** [comment]
Sorry, do not understand your question.

**Comment by psyciknz** [comment]
What problem do you have that the group needs to be set?  I'm curious as I have not seen any user issues when trying to read the logs, or update the config.ini file on the host because of user.

**Comment by IoTPlay** [comment]
Thank you. When I try copy from within the docker container, the file `/opt/paradox/config.master.ini` to the `/opt/paradox/conf` folder, which are also the folder of the host, I get a denied - rights issue.

**Comment by psyciknz** [comment]
ahh ok, I'd tend to just download the config.master.ini from github directly to the host.  

But I'll add you changes.  Does this allow the user to set the UID/GID as part of creating the container?  I'm not sure how to do that.  But means you can set it to a host user.

**Comment by IoTPlay** [comment]
Wait, let me 1st try your approach, will get back to you.

**Comment by IoTPlay** [comment]
Okay, got it working your way, thank you, and sorry !

**Comment by psyciknz** [comment]
No worries, I was interested to see how adding the user in works, as I've used it with other containers, but could not figure out how they do it.
