### ISSUE TITLE
Homie enablement?

### ISSUE THREAD

**Issue by IoTPlay** [psyciknz/ParadoxIP150v2#13]
Thank you for carrying a n the good work with this fork. Got it up on Docker last night.

Are you aware of the developing self discovery and mqtt events standard where both OpenHab and hass subscribes to?

https://homieiot.github.io/

Any chance you might build this in?

**Comment by psyciknz** [comment]
Yes and yes.   I just don’t know how long it might take me.

For openHAB (why I use) it’s almost a requirement as they’ve changed how mqtt is handled
