### ISSUE TITLE
Dockerfile.arm64v8 on Docker Hub?

### ISSUE THREAD

**Issue by IoTPlay** [psyciknz/ParadoxIP150v2#14]
On hub.docker.com I see you have an arm image `arm32v-2.0.10` - but on your code, I see you have also a 64 bit Dockerfile `/Dockerfile.arm64v8`. Do you perhaps have a 64bit version on Arm on Docker hub as well?

**Comment by psyciknz** [comment]
Yeah I haven’t worked out the automated build for all environments yet.
 So the arm64 (yes I do have that as I used to run on an odroid c2) and
arm32 I have to do manually and push to docker hub manually.

**Comment by psyciknz** [comment]
Took me a bit, and I can't automate it which is annoying,  so I have to remember to build it manually and push.  But there's an amd64, arm32v7 and arm64v8 there now.
arm64v8-2.0.13
arm32v7-2.0.13
amd64-2.0.13

If you know how to get the automated builds working, that would be helpful

**Comment by IoTPlay** [comment]
Thank you very very much!!!!

**Comment by IoTPlay** [comment]
Hi, possible you can refresh arm64/armv8 on Docker Hub with latest?

**Comment by psyciknz** [comment]
Not sure if there have been any changes for a while.  I've actually moved to using https://github.com/jpbarraca/pai (and contributing)

**Comment by IoTPlay** [comment]
okay, thank you, I will follow you there..
