### ISSUE TITLE
<Paradox/Events> Output rather in json?

### ISSUE THREAD

**Issue by IoTPlay** [psyciknz/ParadoxIP150v2#16]
Any chance you could output, (with a var in the config.ini) Paradox/Events, and others to json?

Thus, this:
```
Event:Zone OK;SubEvent:Zone 8
```
will become this:
```
{"Event":"Zone OK","SubEvent":"Zone 8"}
```

**Comment by psyciknz** [comment]
That's part of the original system of notifying....which I extended by adding the Zone based topics.  I would have actually preferred to drop it.....but yes it could be modified (and maybe another option to drop it entirely in config.

**Comment by IoTPlay** [comment]
If you are saying ‘Zone based’, could you give an example topic and example msg, I am not sure I follow you.

**Comment by psyciknz** [comment]
```
Topic Paradox/Zones/zone label Sets a status for on of off for each zone. Allows Openhab?Home Assistant to easily configure an item for each zone. Use config item Publish_Zones_OpenClosed to choose between ON/OFF and OPEN/CLOSED for the zone payload message.
```
eg:
```
Paradox/Zone/Front door reed OFF
Paradox/Zone/Family room PIR OFF
Paradox/Zone/Lounge PIR OFF
Paradox/Zone/Bed room PIR OFF
Paradox/Zone/Study PIR OFF
```

**Comment by IoTPlay** [comment]
Okay, missed that, will rather use the Zone.

**Comment by IoTPlay** [comment]
Okay, missed that, will rather use the Zone. close #16

**Comment by IoTPlay** [comment]
Above works well for Zones, per `Paradox/Zone`, but not for `Paradox/Status`. When one for instance arms the alarm, one does not get who armed the alarm like one does with the `Paradox/Events`.

**Comment by psyciknz** [comment]
Have a look at Paradox/Partition/+. That ilists the status of both partitions (and their names if you’re on the .13 version

**Comment by IoTPlay** [comment]
Will have a look, tx.

**Comment by IoTPlay** [comment]
I see the Arm Docker version still @ .10, possible you could upgrade to .13? I tried your Dockerfile, failed, not sure how you did it.

**Comment by psyciknz** [comment]
see #14
