### ISSUE TITLE
EVO192 integration

### ISSUE THREAD

**Issue by kunago** [psyciknz/ParadoxIP150v2#4]
By any chance, do you have an idea how to or simply whether implementation of EVO192 would be feasible?

**Comment by psyciknz** [comment]
Are you still looking?  Unsure how compatible the devices are.  You could give it a go and see how it responds.

**Comment by kunago** [comment]
I was looking for a response, I tried to figure it out, even tested the code but did not have any success unfortunately.

**Comment by bwibwi13** [comment]
Hello, I have just acquired an EVO192 with IP150 module.
I tried to run the script and here is the result:
`...
INFO:root:State02:Connecting to IP Module
[Errno 104] Connection reset by peer
INFO:root:Connecting to 192.168.0.14
INFO:root:Logging into alarm system...
DEBUG:root:32->   0xaa 0x4 0x0 0x3 0x8 0xf0 0x0 0xa 0xee 0xee 0xee 0xee 0xee 0xee 0xee 0xee 0x61 0x62 0x63 0x64 0xee 0xee 0xee 0xee 0xee 0xee 0xee 0xee 0xee 0xee 0xee 0xee
...`
Do you think we have a chance that this would be compatible ?

**Comment by psyciknz** [comment]
Unlikely.  You'll probably have more luck with https://github.com/jpbarraca/pai   Which even I use at the moment rather than ParadoxIP150

**Comment by bwibwi13** [comment]
@psyciknz Thanks for the quick response and for the reference to pai.
I indeed found it meanwhile and started testing it.
Thanks a lot :)

**Comment by kunago** [comment]
I implement pai in one of my projects and it seems to work quite well.
