### ISSUE TITLE
MG5050, IP100 and Docker

### ISSUE THREAD

**Issue by blademckain** [psyciknz/ParadoxIP150v2#5]
Hi all, 
i have MG5050 and IP100 module.
wanna exeute your script as a Docker service, it is possibile?
what command i have to insert in the paradoxip.service ??

**Comment by psyciknz** [comment]
Oh I don’t actually  have s built version in a registry, I should do one.

So at the moment you probably have to git clone then use docker build

Thre .service file is for running out of docker
