### ISSUE TITLE
Openhab mqtt.things and alarm.items example?

### ISSUE THREAD

**Issue by blademckain** [psyciknz/ParadoxIP150v2#6]
Hi,
can someone post his configuration files as a basis for configuration in openhab?
i need the
mqtt.think and the alarm.item

**Comment by psyciknz** [comment]
You mean like in this folder? 
https://github.com/psyciknz/ParadoxIP150v2/tree/master/HomeAutomation

**Comment by blademckain** [comment]
yep
but i think is the old mqtt version
any example for the new mqtt 2.4 binding?

**Comment by psyciknz** [comment]
No, I';ve not moved to that yet, as there were issues with it.  So someone else with have to figure out all the things.  If you do, you can post them here, and I'll include them
